name: '2dam1ev'

services:
  mysql:
    image: mysql:latest
    env_file:
      - ./.env
    volumes:
      - ./dbCreation.sql:/docker-entrypoint-initdb.d/dbCreation.sql
      - data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  data:
